/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 botella.glb --types
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Ramazzotti_Atlas_0: THREE.Mesh
  }
  materials: {
    Atlas: THREE.MeshStandardMaterial
  }
}

export function Botella(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./model/botella.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Ramazzotti_Atlas_0.geometry} material={materials.Atlas} position={[0, 0, 0]} scale={0.05}/>
      </group>
    </group>
  )
}

useGLTF.preload('/botella.glb')
