/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 mug.glb --types
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Center, Environment, MeshTransmissionMaterial, useGLTF, useMatcapTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useControls } from 'leva'
import { Physics, RigidBody } from '@react-three/rapier'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Curve: THREE.Mesh
  }
  materials: {
    ['SVGMat.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const logoRef = useRef<any>(null)

  // const materialProps = useControls({
      //   thickness: { value: 4.6, min: 0, max: 20 },
      //   roughness: { value: 0.6, min: 0, max: 1, step: 0.1 },
      //   clearcoat: { value: 0.4, min: 0, max: 1, step: 0.1 },
      //   clearcoatRoughness: { value: 0, min: 0, max: 1, step: 0.1 },
      //   transmission: { value: 1, min: 0.9, max: 1, step: 0.01 },
      //   ior: { value: 1.40, min: 1, max: 2.3, step: 0.05 },
      //   envMapIntensity: { value: 39, min: 0, max: 100, step: 1 },
      //   color: '#ffffff',
      //   attenuationTint: '#ffe79e',
      //   attenuationDistance: { value: 0.40, min: 0, max: 1 }
      // })

      // const envProps = useControls({ background: false })
  
  const { nodes, materials } = useGLTF('./model/mug.glb') as GLTFResult;

  // const envProps = useControls({ background: false })
  const envProps = {background: false}
  return (
    <Center>
      <group {...props} dispose={null} position={[0, 0, 0]}>        
            {/* <RigidBody>
              <mesh geometry={nodes.Curve.geometry} rotation={[1.571, 0, 0]} scale={0.7} ref={logoRef}>
                <meshPhysicalMaterial {...materialProps} />
              </mesh>              
            </RigidBody> */}
            <RigidBody type='fixed'>
              <mesh geometry={nodes.Curve.geometry} rotation={[1.571, 0, 0]} scale={0.7} ref={logoRef}>
              <MeshTransmissionMaterial
              backside
              backsideThickness={4}
              thickness={3}
              chromaticAberration={0.5}
              anisotropicBlur={0.05}
              iridescence={1}
              iridescenceIOR={1}
              iridescenceThicknessRange={[0, 1400]}
              clearcoatRoughness={0}
              clearcoat={1}
              envMapIntensity={1} 
              distortionScale={0} 
              temporalDistortion={0}                
              />
              </mesh>              
            </RigidBody>        
        <Environment {...envProps} files="./adams_place_bridge_1k.hdr" />
      </group>
    </Center>
  )
}

useGLTF.preload('./model/mug.glb')
